symfony:
  build: symfony/
  links:
#    - redis
    - db
    - elasticsearch
#    - nodejs
  volumes:
    - ./symfony/code:/var/www
  volumes_from:
    - data

data:
  image: busybox
  volumes:
    - /var/www/omega/app/cache
    - /var/www/omega/app/logs

nginx:
  build: nginx/
  ports:
    - 80:80
  links:
    - fpm
  volumes_from:
    - symfony
  environment:
    <APP_SERVER_NAME>: liveapps2.local

db:
  image: mysql
  ports:
    - 3306:3306
  environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: livedb
      MYSQL_USER: root
      MYSQL_PASSWORD: root

fpm:
  build: php-fpm/
  links:
#    - redis
    - db
    - elasticsearch
  volumes_from:
    - symfony
  environment:
    APP_SERVER_NAME: liveapps2.local

php5.5-fpm:
  build: php5.5-fpm/

#redis:
#  image: redis:2.8.13

elasticsearch:
  image: elasticsearch

#nodejs:
#  build: nodejs/
#  volumes:
#    - ./symfony/code:/var/www
#  volumes_from:
#    - symfony

#mongo:
#  image: mongo:3.0.4
#  ports:
#    - "27017:27017"